[ts-sdk] Fix type definition for MakeMoveVec (#11655)
## Description 

Fix a bug where there is a type mismatch in the user input and BCS
schema

## Test Plan 

Added an e2e test to add `type` hint for `makeMoveVec`, without the
changes in this PR the test will fail with the following error

```
 FAIL  test/e2e/object-vector.test.ts > Test Move call with a vector of objects as input > Test object vector
Error: Incorrect data passed into enum "TypeTag", expected object with properties: "bool | u8 | u64 | u128 | address | signer | vector | struct | u16 | u32 | u256".
Received: ""0x60c831c44574dab69122c964cedc03bf18a23680a713c3ea41240b066187e26d::entry_point_vector::Obj""
 ❯ _BCS.encodeEnum ../bcs/src/index.ts:1269:17
    1267|         }
    1268|         if (typeof data !== "object") {
    1269|           throw new Error(
       |                 ^
    1270|             `Incorrect data passed into enum "$…
    1271|               " | "
```

After this PR, the test will pass


---
If your changes are not user-facing and not a breaking change, you can
skip the following section. Otherwise, please indicate what changed, and
then add to the Release Notes section as highlighted during the release
process.

### Type of Change (Check all that apply)

- [ ] user-visible impact
- [ ] breaking change for a client SDKs
- [ ] breaking change for FNs (FN binary must upgrade)
- [ ] breaking change for validators or node operators (must upgrade
binaries)
- [ ] breaking change for on-chain data layout
- [ ] necessitate either a data wipe or data migration

### Release notes