[docs] Add comments regarding type argument instantiation (#11877)
## Description 

This PR adds a comment regarding the necessity of providing type
arguments to Move calls.

I ran into this issue while testing the examples provided in the example
[Defi](https://github.com/MystenLabs/sui/blob/main/sui_programmability/examples/defi/sources/escrow.move)
package:

* calling the `create` entry function, via `sui client call`, without
instantiating both of its type arguments resulted in
  ```
  Error calling module: Failure {
      error: "VMVerificationOrDeserializationError in command 0",
  }
  ```

Adding the required type arguments fixes the issue.

## Test Plan 

Since this very small PR consists of comments only, I believe no tests
are needed.

---

### Type of Change (Check all that apply)

- [ ] user-visible impact
- [ ] breaking change for a client SDKs
- [ ] breaking change for FNs (FN binary must upgrade)
- [ ] breaking change for validators or node operators (must upgrade
binaries)
- [ ] breaking change for on-chain data layout
- [ ] necessitate either a data wipe or data migration

### Release notes

---------

Co-authored-by: Ashok Menon <ashok@mystenlabs.com>