fix(sui-json-rpc-types): fix `Display` of `SuiTransactionBlockResponse` with empty balance changes (#21322)
Formatting an instance of `SuiTransactionBlockResponse` using an empty
format `{}` panics if the instance contains an empty vector of balance
changes, which occurs for system transactions like
`ConsensusCommitPrologueV3`.

Porting over https://github.com/iotaledger/iota/issues/5366

## Description 

_Describe the changes or additions included in this PR._

In the `Display` implementation for `SuiTransactionBlockResponse`, add a
check for a vector of balance changes being non-empty -- only then a
build a table and safely operate on it. A similar check is done in the
`Display` implementation for `SuiTransactionBlockEvents`.

## Test plan 

_How did you test the new or updated feature?_

Added `test_display_transaction_block_with_empty_balance_changes` test:

```console
cargo test -p sui-json-rpc-tests test_display_transaction_block_with_empty_balance_changes -- --exact
```

Running this test on the `main` branch without proposed changes panics:

```
---- test_display_transaction_block_with_empty_balance_changes stdout ----
thread 'test_display_transaction_block_with_empty_balance_changes' panicked at /home/rom/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tabled-0.12.2/src/grid/records/records_mut.rs:25:18:
index out of bounds: the len is 0 but the index is 0
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

---

## Release notes

Check each box that your changes affect. If none of the boxes relate to
your changes, release notes aren't required.

For each box you select, include information after the relevant heading
that describes the impact of your changes that a user might notice and
any actions they must take to implement updates.

- [ ] Protocol: 
- [ ] Nodes (Validators and Full nodes): 
- [ ] gRPC:
- [ ] JSON-RPC: 
- [ ] GraphQL: 
- [ ] CLI: 
- [ ] Rust SDK: