indexer-alt: error on unexpected pipeline config
## Description

TOML deserialization ignores fields that are not relevant to the struct
being targeted. Given all the fields in our config have default values,
this behaviour can cause confusion because it means that a typo on a
field name will result in the value being ignored and replaced with its
default value without warning.

It's tough to change this behaviour wholesale (to detect and error on
any unrecognised field name), but this chane tries to bridge most of the
gap by detecting unexpected pipeline configurations and erroring for
those.

## Test plan

Run the indexer on a config with typos in its pipeline configs. It will
now produce an error explaining that it doesn't recognise those configs:

```
sui$ cargo run -p sui-indexer-alt -- indexer --config /tmp/tx.toml --last-checkpoint 10000 --remote-store-url 'https://checkpoints.mainnet.sui.io'
Error: Unexpected pipeline configurations:
[tx-calls]

[tx-affected-objects]
collect-interval-ms = 5000
```