indexer-alt: ensure `--pipeline` flags are only known pipelines
## Description

Produce an error if the a value is passed to the `--pipeline` flag that
is not supported at all. This should catch pipeline name typos more
easily.

## Test Plan

Test various configurations of the indexer (no pipeline filtering, valid
filtering, and invalid filtering):

```
sui$ cargo run -p sui-indexer-alt --release --                                 \
  --database-url postgres://postgres:postgrespw@localhost:5432/sui_indexer_alt \
  indexer --remote-store-url https://checkpoints.mainnet.sui.io                \
  --last-checkpoint 100000 --consistent-range 1000

sui$ cargo run -p sui-indexer-alt --release --                                 \
  --database-url postgres://postgres:postgrespw@localhost:5432/sui_indexer_alt \
  indexer --remote-store-url https://checkpoints.mainnet.sui.io                \
  --last-checkpoint 100000 --consistent-range 1000                             \
  --pipeline sum_obj_types --pipeline wal_obj_types

sui$ cargo run -p sui-indexer-alt --release --                                 \
  --database-url postgres://postgres:postgrespw@localhost:5432/sui_indexer_alt \
  indexer --remote-store-url https://checkpoints.mainnet.sui.io                \
  --last-checkpoint 100000 --consistent-range 1000                             \
  --pipeline i_dont_exist
[...]
Error: Failed to start indexer

Caused by:
    Tried to enable pipelines that this indexer does not know about: {
        "i_dont_exist",
    }
```